### ISSUE TITLE
Improve merge documentation

### ISSUE THREAD

**Issue by JN-Jones** [mybb/docs.mybb.com#36] opened 2014-08-31 16:07 UTC
As I'm working on it atm I've found a few things we should change/add:
- [x] `The latest publicly released version of the MyBB Merge System only imports to MyBB 1.6.x. The version for importing to MyBB 1.2 is no longer supported.` Nope - 1.2, 1.4 AND 1.6 aren't supported anymore :P
- [x] Sometimes it may happen that you get a "Website not reachable" error while the merge (I got it with phpBB3, post module). This is due the Stack size, adding the following code to httpd.conf and restarting Apache fixes it.

```
<IfModule mpm_winnt_module>
   ThreadStackSize 8*1024*1024
</IfModule>
```

Edit: not always, see https://github.com/mybb/merge-system/issues/112
- [x] Update list of supported modules
- [x] Add "use r&r" https://github.com/mybb/merge-system/issues/31
- [ ] How To fix attachment permissions (especially those cause by .htaccess)

Note that @JovanJ and me will extend this list while working on the merge system.

**Comment by JN-Jones** [comment] 2014-09-12 19:53
I fixed a few things, need to add a few infos about the attachment/.htaccess thing and convert the "Running the Merge System" part (take a few screens etc).

**Comment by JoshHarmon** [comment] 2015-08-19 06:13
@JN-Jones Would you say http://docs.mybb.com/1.8/merge/troubleshooting/#attachment-permissions-are-wrong solves the last point or no?

If not, what else should be mentioned (I'm not an expert on the merge system, but want to document it.)

**Comment by JN-Jones** [comment] 2015-08-19 09:27
The old documentation had some images for the different steps. Apart from that I don't know anything that could be added.

**Comment by andrewjs18** [comment] 2018-02-19 22:01
closing this as the issue is almost 4 years old and the merge system development has been stagnant for quite some time.

**Closed as completed by andrewjs18** 2018-02-19 22:01 UTC
